/* Auto-generated search index — 142 sections dari 9 halaman */
const SEARCH_INDEX = [
    {
        id: "gerak-lurus",
        url: "mekanika.html#gerak-lurus",
        title: "Kinematika — Gerak Lurus",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Kinematika mempelajari bagaimana benda bergerak tanpa mempersoalkan penyebabnya. Besaran pokok: posisi , kecepatan , percepatan , dan waktu .",
        keywords: [
            "Persamaan GLB",
            "Kecepatan",
            "Perpindahan",
            "Kecepatan–Posisi",
            "Rata-rata",
            "Gerak Lurus Beraturan (GLB)",
            "Gerak Lurus Berubah Beraturan (GLBB)",
        ],
        searchText:
            "kinematika — gerak lurus kinematika mempelajari bagaimana benda bergerak tanpa mempersoalkan penyebabnya. besaran pokok: posisi , kecepatan , percepatan , dan waktu . persamaan glb kecepatan perpindahan kecepatan–posisi rata-rata gerak lurus beraturan (glb) gerak lurus berubah beraturan (glbb)",
    },
    {
        id: "gerak-melingkar",
        url: "mekanika.html#gerak-melingkar",
        title: "Gerak Melingkar",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Benda bergerak di lintasan lingkaran. Selalu ada percepatan sentripetal yang mengarah ke pusat.",
        keywords: [
            "Kecepatan Sudut",
            "Kecepatan Linier",
            "Percepatan Sentripetal",
            "Gaya Sentripetal",
        ],
        searchText:
            "gerak melingkar benda bergerak di lintasan lingkaran. selalu ada percepatan sentripetal yang mengarah ke pusat. kecepatan sudut kecepatan linier percepatan sentripetal gaya sentripetal",
    },
    {
        id: "gerak-parabola",
        url: "mekanika.html#gerak-parabola",
        title: "Gerak Parabola",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Superposisi GLB (horizontal) dan GLBB (vertikal). Analisis komponen secara terpisah.",
        keywords: ["Jangkauan Maks (R)", "Ketinggian Maks (H)", "Waktu Total"],
        searchText:
            "gerak parabola superposisi glb (horizontal) dan glbb (vertikal). analisis komponen secara terpisah. jangkauan maks (r) ketinggian maks (h) waktu total",
    },
    {
        id: "ghs",
        url: "mekanika.html#ghs",
        title: "Gerak Harmonik Sederhana (GHS)",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "GHS terjadi ketika gaya pemulih sebanding dengan simpangan: . Geraknya berosilasi periodik.",
        keywords: ["Simpangan", "Kecepatan", "Pegas: ω & T", "Bandul: ω & T", "Energi dalam GHS"],
        searchText:
            "gerak harmonik sederhana (ghs) ghs terjadi ketika gaya pemulih sebanding dengan simpangan: . geraknya berosilasi periodik. simpangan kecepatan pegas: ω & t bandul: ω & t energi dalam ghs",
    },
    {
        id: "hukum-newton",
        url: "mekanika.html#hukum-newton",
        title: "Dinamika — Hukum Newton",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Benda diam tetap diam dan benda bergerak tetap bergerak lurus beraturan jika resultan gaya = 0.",
        keywords: ["Hukum I — Inersia", "Hukum II — F = ma", "Hukum III — Aksi–Reaksi"],
        searchText:
            "dinamika — hukum newton benda diam tetap diam dan benda bergerak tetap bergerak lurus beraturan jika resultan gaya = 0. hukum i — inersia hukum ii — f = ma hukum iii — aksi–reaksi",
    },
    {
        id: "momentum",
        url: "mekanika.html#momentum",
        title: "Momentum & Impuls",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Momentum Linier", "Impuls", "Kekekalan Momentum", "Koefisien Restitusi"],
        searchText:
            "momentum & impuls  momentum linier impuls kekekalan momentum koefisien restitusi",
    },
    {
        id: "energi",
        url: "mekanika.html#energi",
        title: "Usaha & Energi",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: [
            "Usaha",
            "Energi Kinetik",
            "Energi Pot. Gravitasi",
            "Energi Pot. Pegas",
            "Teorema Usaha–Energi",
            "Daya",
        ],
        searchText:
            "usaha & energi  usaha energi kinetik energi pot. gravitasi energi pot. pegas teorema usaha–energi daya",
    },
    {
        id: "gesekan",
        url: "mekanika.html#gesekan",
        title: "Gaya Gesekan",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Gesekan Statis (maks)", "Gesekan Kinetis"],
        searchText: "gaya gesekan  gesekan statis (maks) gesekan kinetis",
    },
    {
        id: "rotasi",
        url: "mekanika.html#rotasi",
        title: "Mekanika Rotasi — Torsi & Momen Inersia",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Torsi", "Hukum II Rotasi", "Momen Inersia", "Ek Rotasi", "Teorema Steiner"],
        searchText:
            "mekanika rotasi — torsi & momen inersia  torsi hukum ii rotasi momen inersia ek rotasi teorema steiner",
    },
    {
        id: "momentum-sudut",
        url: "mekanika.html#momentum-sudut",
        title: "Momentum Sudut",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Momentum Sudut", "Kekekalan Momentum Sudut"],
        searchText: "momentum sudut  momentum sudut kekekalan momentum sudut",
    },
    {
        id: "gravitasi",
        url: "mekanika.html#gravitasi",
        title: "Gravitasi — Hukum Gravitasi Newton",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: [
            "Gaya Gravitasi Universal",
            "Medan Gravitasi",
            "Potensial Gravitasi",
            "Energi Potensial",
            "Kecepatan Lepas",
        ],
        searchText:
            "gravitasi — hukum gravitasi newton  gaya gravitasi universal medan gravitasi potensial gravitasi energi potensial kecepatan lepas",
    },
    {
        id: "kepler",
        url: "mekanika.html#kepler",
        title: "Hukum Kepler",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Setiap planet bergerak dalam orbit elips dengan Matahari di salah satu titik fokusnya.",
        keywords: ["Hukum I — Orbit Elips", "Hukum II — Luas Sama", "Hukum III — T² ∝ a³"],
        searchText:
            "hukum kepler setiap planet bergerak dalam orbit elips dengan matahari di salah satu titik fokusnya. hukum i — orbit elips hukum ii — luas sama hukum iii — t² ∝ a³",
    },
    {
        id: "orbit",
        url: "mekanika.html#orbit",
        title: "Gerak Orbit & Satelit",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Kecepatan Orbital", "Periode Orbit", "Energi Total Orbit", "Orbit GSO Bumi"],
        searchText:
            "gerak orbit & satelit  kecepatan orbital periode orbit energi total orbit orbit gso bumi",
    },
    {
        id: "hidrostatika",
        url: "mekanika.html#hidrostatika",
        title: "Mekanika Fluida — Hidrostatika",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Tekanan", "Tekanan Hidrostatis", "Hukum Pascal"],
        searchText: "mekanika fluida — hidrostatika  tekanan tekanan hidrostatis hukum pascal",
    },
    {
        id: "archimedes",
        url: "mekanika.html#archimedes",
        title: "Hukum Archimedes",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: ["Gaya Apung"],
        searchText: "hukum archimedes  gaya apung",
    },
    {
        id: "hidrodinamika",
        url: "mekanika.html#hidrodinamika",
        title: "Hidrodinamika & Bernoulli",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "Kecepatan semburan dari lubang di tangki:",
        keywords: [
            "Persamaan Kontinuitas",
            "Persamaan Bernoulli",
            "Teorema Torricelli",
            "Efek Venturi",
            "Gaya Angkat (Lift)",
        ],
        searchText:
            "hidrodinamika & bernoulli kecepatan semburan dari lubang di tangki: persamaan kontinuitas persamaan bernoulli teorema torricelli efek venturi gaya angkat (lift)",
    },
    {
        id: "elastisitas",
        url: "mekanika.html#elastisitas",
        title: "Elastisitas & Modulus Young",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet: "",
        keywords: [
            "Hukum Hooke",
            "Tegangan (Stress)",
            "Regangan (Strain)",
            "Modulus Young",
            "Pegas Seri",
            "Pegas Paralel",
        ],
        searchText:
            "elastisitas & modulus young  hukum hooke tegangan (stress) regangan (strain) modulus young pegas seri pegas paralel",
    },
    {
        id: "osilasi",
        url: "mekanika.html#osilasi",
        title: "Osilasi Teredam",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Terjadi ketika gaya resistif (gesekan/viskositas) mengurangi amplitudo secara bertahap.",
        keywords: ["Amplitudo Teredam"],
        searchText:
            "osilasi teredam terjadi ketika gaya resistif (gesekan/viskositas) mengurangi amplitudo secara bertahap. amplitudo teredam",
    },
    {
        id: "contoh-soal",
        url: "mekanika.html#contoh-soal",
        title: "Contoh Soal",
        topic: "mekanika",
        topicLabel: "Mekanika",
        icon: "settings",
        snippet:
            "Meriam di puncak lereng menembakkan peluru pada . Tentukan: (a) jangkauan sepanjang lereng, (b) sudut optimal , dan (c) jangkauan maksimum.",
        keywords: [],
        searchText:
            "contoh soal meriam di puncak lereng menembakkan peluru pada . tentukan: (a) jangkauan sepanjang lereng, (b) sudut optimal , dan (c) jangkauan maksimum. ",
    },
    {
        id: "teori-kinetik",
        url: "termodinamika.html#teori-kinetik",
        title: "Teori Kinetik Gas",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet:
            "Dalam kenyataan, gas nyata mendekati gas ideal pada tekanan rendah dan suhu tinggi.",
        keywords: ["Gas Ideal"],
        searchText:
            "teori kinetik gas dalam kenyataan, gas nyata mendekati gas ideal pada tekanan rendah dan suhu tinggi. gas ideal",
    },
    {
        id: "persamaan-gas",
        url: "termodinamika.html#persamaan-gas",
        title: "Persamaan Keadaan Gas",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Hukum Gas Ideal", "Persamaan Keadaan Gas"],
        searchText: "persamaan keadaan gas  hukum gas ideal persamaan keadaan gas",
    },
    {
        id: "kecepatan-molekul",
        url: "termodinamika.html#kecepatan-molekul",
        title: "Kecepatan Molekul Gas",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: [
            "Kecepatan RMS",
            "Kecepatan Paling Mungkin",
            "Kecepatan Rata-rata",
            "Hubungan Kecepatan",
            "Tekanan Gas dari Teori Kinetik",
            "Kecepatan Molekul Gas",
        ],
        searchText:
            "kecepatan molekul gas  kecepatan rms kecepatan paling mungkin kecepatan rata-rata hubungan kecepatan tekanan gas dari teori kinetik kecepatan molekul gas",
    },
    {
        id: "ekipartisi",
        url: "termodinamika.html#ekipartisi",
        title: "Teorema Ekipartisi Energi",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Hubungan C_p dan C_v", "Teorema Ekipartisi Energi"],
        searchText: "teorema ekipartisi energi  hubungan c_p dan c_v teorema ekipartisi energi",
    },
    {
        id: "hukum-termo",
        url: "termodinamika.html#hukum-termo",
        title: "Hukum-Hukum Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: [],
        searchText: "hukum-hukum termodinamika  ",
    },
    {
        id: "hukum-0",
        url: "termodinamika.html#hukum-0",
        title: "Hukum ke-0 Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "Hukum ini mendefinisikan suhu secara operasional dan menjadi dasar termometer.",
        keywords: ["Hukum ke-0 Termodinamika"],
        searchText:
            "hukum ke-0 termodinamika hukum ini mendefinisikan suhu secara operasional dan menjadi dasar termometer. hukum ke-0 termodinamika",
    },
    {
        id: "hukum-1",
        url: "termodinamika.html#hukum-1",
        title: "Hukum I Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Hukum I — Kekekalan Energi", "Kerja Ekspansi Gas", "Hukum I Termodinamika"],
        searchText:
            "hukum i termodinamika  hukum i — kekekalan energi kerja ekspansi gas hukum i termodinamika",
    },
    {
        id: "hukum-2",
        url: "termodinamika.html#hukum-2",
        title: "Hukum II Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet:
            "Tidak mungkin membuat mesin yang bekerja dalam siklus yang semata-mata menyerap kalor dari reservoir dan mengubahnya seluruhnya menjadi kerja.",
        keywords: ["Hukum II Termodinamika", "Pernyataan Kelvin-Planck", "Pernyataan Clausius"],
        searchText:
            "hukum ii termodinamika tidak mungkin membuat mesin yang bekerja dalam siklus yang semata-mata menyerap kalor dari reservoir dan mengubahnya seluruhnya menjadi kerja. hukum ii termodinamika pernyataan kelvin-planck pernyataan clausius",
    },
    {
        id: "hukum-3",
        url: "termodinamika.html#hukum-3",
        title: "Hukum III Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "Implikasi: mustahil mencapai suhu nol mutlak (0 K) melalui proses terbatas.",
        keywords: ["Hukum III Termodinamika"],
        searchText:
            "hukum iii termodinamika implikasi: mustahil mencapai suhu nol mutlak (0 k) melalui proses terbatas. hukum iii termodinamika",
    },
    {
        id: "proses",
        url: "termodinamika.html#proses",
        title: "Proses Termodinamika",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Persamaan Adiabatik", "Versi Lain", "Kerja Adiabatik"],
        searchText: "proses termodinamika  persamaan adiabatik versi lain kerja adiabatik",
    },
    {
        id: "diagram-pv",
        url: "termodinamika.html#diagram-pv",
        title: "Diagram P-V",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet:
            "V P Isotermal (T konstan) Isobarik Isokhorik Adiabatik Kurva P-V untuk keempat proses termodinamika. Luas di bawah kurva = Kerja yang dilakukan gas.",
        keywords: ["Diagram P-V"],
        searchText:
            "diagram p-v v p isotermal (t konstan) isobarik isokhorik adiabatik kurva p-v untuk keempat proses termodinamika. luas di bawah kurva = kerja yang dilakukan gas. diagram p-v",
    },
    {
        id: "mesin-kalor",
        url: "termodinamika.html#mesin-kalor",
        title: "Mesin Kalor & Siklus Carnot",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet:
            "Siklus Carnot adalah siklus ideal yang paling efisien, terdiri dari 2 proses isotermal dan 2 proses adiabatik.",
        keywords: ["Efisiensi Mesin Kalor", "Efisiensi Carnot (Maksimum)", "Siklus Carnot"],
        searchText:
            "mesin kalor & siklus carnot siklus carnot adalah siklus ideal yang paling efisien, terdiri dari 2 proses isotermal dan 2 proses adiabatik. efisiensi mesin kalor efisiensi carnot (maksimum) siklus carnot",
    },
    {
        id: "efisiensi",
        url: "termodinamika.html#efisiensi",
        title: "Efisiensi Berbagai Mesin",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Efisiensi Berbagai Mesin"],
        searchText: "efisiensi berbagai mesin  efisiensi berbagai mesin",
    },
    {
        id: "pendingin",
        url: "termodinamika.html#pendingin",
        title: "Mesin Pendingin & Pompa Kalor",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: [
            "Koefisien Kinerja (Pendingin)",
            "Koefisien Kinerja (Pompa Kalor)",
            "Mesin Pendingin & Pompa Kalor",
        ],
        searchText:
            "mesin pendingin & pompa kalor  koefisien kinerja (pendingin) koefisien kinerja (pompa kalor) mesin pendingin & pompa kalor",
    },
    {
        id: "entropi",
        url: "termodinamika.html#entropi",
        title: "Entropi",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "",
        keywords: ["Perubahan Entropi", "Entropi Boltzmann"],
        searchText: "entropi  perubahan entropi entropi boltzmann",
    },
    {
        id: "transfer-kalor",
        url: "termodinamika.html#transfer-kalor",
        title: "Transfer Kalor",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet: "Perpindahan kalor melalui kontak langsung tanpa aliran materi.",
        keywords: ["Konduksi", "Konveksi", "Radiasi"],
        searchText:
            "transfer kalor perpindahan kalor melalui kontak langsung tanpa aliran materi. konduksi konveksi radiasi",
    },
    {
        id: "osn-soal",
        url: "termodinamika.html#osn-soal",
        title: "Contoh Soal",
        topic: "termodinamika",
        topicLabel: "Termodinamika",
        icon: "thermometer",
        snippet:
            "Sebuah mesin kalor menjalankan siklus yang terdiri dari empat proses berikut pada 2 mol gas ideal monoatomik ():",
        keywords: [],
        searchText:
            "contoh soal sebuah mesin kalor menjalankan siklus yang terdiri dari empat proses berikut pada 2 mol gas ideal monoatomik (): ",
    },
    {
        id: "gelombang-mekanik",
        url: "gelombang.html#gelombang-mekanik",
        title: "Sifat Dasar Gelombang",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Arah getaran tegak lurus terhadap arah rambat. Contoh: gelombang tali, gelombang cahaya.",
        keywords: [
            "Persamaan Dasar Gelombang",
            "Bilangan Gelombang",
            "Gelombang Transversal",
            "Gelombang Longitudinal",
        ],
        searchText:
            "sifat dasar gelombang arah getaran tegak lurus terhadap arah rambat. contoh: gelombang tali, gelombang cahaya. persamaan dasar gelombang bilangan gelombang gelombang transversal gelombang longitudinal",
    },
    {
        id: "persamaan-gelombang",
        url: "gelombang.html#persamaan-gelombang",
        title: "Persamaan Gelombang",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "",
        keywords: [
            "Persamaan Gelombang Berjalan",
            "Persamaan Diferensial Gelombang",
            "Persamaan Gelombang",
        ],
        searchText:
            "persamaan gelombang  persamaan gelombang berjalan persamaan diferensial gelombang persamaan gelombang",
    },
    {
        id: "energi-gelombang",
        url: "gelombang.html#energi-gelombang",
        title: "Energi & Intensitas Gelombang",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "",
        keywords: [
            "Intensitas",
            "Intensitas Sumber Titik",
            "Hubungan Intensitas-Amplitudo",
            "Intensitas Gelombang Mekanik",
            "Energi & Intensitas Gelombang",
        ],
        searchText:
            "energi & intensitas gelombang  intensitas intensitas sumber titik hubungan intensitas-amplitudo intensitas gelombang mekanik energi & intensitas gelombang",
    },
    {
        id: "bunyi",
        url: "gelombang.html#bunyi",
        title: "Gelombang Bunyi",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Bunyi adalah gelombang longitudinal mekanik yang memerlukan medium untuk merambat. Bunyi terdiri dari rapatan (compressions) dan renggangan (rarefacti",
        keywords: [],
        searchText:
            "gelombang bunyi bunyi adalah gelombang longitudinal mekanik yang memerlukan medium untuk merambat. bunyi terdiri dari rapatan (compressions) dan renggangan (rarefacti ",
    },
    {
        id: "kecepatan-bunyi",
        url: "gelombang.html#kecepatan-bunyi",
        title: "Cepat Rambat Bunyi",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "",
        keywords: [
            "Dalam Gas Ideal",
            "Koreksi Suhu (Udara)",
            "Dalam Zat Padat",
            "Dalam Zat Cair",
            "Cepat Rambat Bunyi",
        ],
        searchText:
            "cepat rambat bunyi  dalam gas ideal koreksi suhu (udara) dalam zat padat dalam zat cair cepat rambat bunyi",
    },
    {
        id: "intensitas-bunyi",
        url: "gelombang.html#intensitas-bunyi",
        title: "Intensitas & Taraf Intensitas Bunyi",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "",
        keywords: [
            "Taraf Intensitas Bunyi",
            "Selisih Taraf",
            "Intensitas & Taraf Intensitas Bunyi",
        ],
        searchText:
            "intensitas & taraf intensitas bunyi  taraf intensitas bunyi selisih taraf intensitas & taraf intensitas bunyi",
    },
    {
        id: "doppler",
        url: "gelombang.html#doppler",
        title: "Efek Doppler",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Efek Doppler adalah perubahan frekuensi yang diamati ketika sumber bunyi atau pengamat bergerak relatif satu terhadap lainnya.",
        keywords: [
            "Frekuensi yang Diamati",
            "Konstruktif (Amplitudo Maks)",
            "Destruktif (Amplitudo = 0)",
        ],
        searchText:
            "efek doppler efek doppler adalah perubahan frekuensi yang diamati ketika sumber bunyi atau pengamat bergerak relatif satu terhadap lainnya. frekuensi yang diamati konstruktif (amplitudo maks) destruktif (amplitudo = 0)",
    },
    {
        id: "pelayangan",
        url: "gelombang.html#pelayangan",
        title: "Pelayangan Gelombang (Beats)",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Ketika dua gelombang dengan frekuensi hampir sama bertumpang tindih, amplitudo resultannya berosilasi secara periodik.",
        keywords: ["Frekuensi Pelayangan", "Persamaan Superposisi", "Pelayangan Gelombang (Beats)"],
        searchText:
            "pelayangan gelombang (beats) ketika dua gelombang dengan frekuensi hampir sama bertumpang tindih, amplitudo resultannya berosilasi secara periodik. frekuensi pelayangan persamaan superposisi pelayangan gelombang (beats)",
    },
    {
        id: "stasioner",
        url: "gelombang.html#stasioner",
        title: "Gelombang Stasioner",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Gelombang stasioner terbentuk dari superposisi dua gelombang identik yang merambat berlawanan arah.",
        keywords: ["Persamaan Gelombang Stasioner"],
        searchText:
            "gelombang stasioner gelombang stasioner terbentuk dari superposisi dua gelombang identik yang merambat berlawanan arah. persamaan gelombang stasioner",
    },
    {
        id: "dawai",
        url: "gelombang.html#dawai",
        title: "Dawai / Senar yang Bergetar",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "Kedua ujung dawai adalah simpul (node). Frekuensi harmonik:",
        keywords: ["Harmonik ke-n pada Dawai", "Dawai / Senar yang Bergetar"],
        searchText:
            "dawai / senar yang bergetar kedua ujung dawai adalah simpul (node). frekuensi harmonik: harmonik ke-n pada dawai dawai / senar yang bergetar",
    },
    {
        id: "pipa-organa",
        url: "gelombang.html#pipa-organa",
        title: "Pipa Organa",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "Kedua ujung adalah perut (antinode).",
        keywords: ["Pipa Organa"],
        searchText: "pipa organa kedua ujung adalah perut (antinode). pipa organa",
    },
    {
        id: "resonansi",
        url: "gelombang.html#resonansi",
        title: "Resonansi",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet: "",
        keywords: ["Resonansi"],
        searchText: "resonansi  resonansi",
    },
    {
        id: "osn-soal",
        url: "gelombang.html#osn-soal",
        title: "Contoh Soal",
        topic: "gelombang",
        topicLabel: "Gelombang & Bunyi",
        icon: "radio",
        snippet:
            "Sebuah garpu tala frekuensi digetarkan dan didekatkan ke mulut pipa silinder vertikal yang salah satu ujungnya tertutup air. Air dalam pipa dapat diat",
        keywords: [],
        searchText:
            "contoh soal sebuah garpu tala frekuensi digetarkan dan didekatkan ke mulut pipa silinder vertikal yang salah satu ujungnya tertutup air. air dalam pipa dapat diat ",
    },
    {
        id: "elektrostatika",
        url: "elektromagnetisme.html#elektrostatika",
        title: "Elektrostatika",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Gaya Coulomb", "Hukum Coulomb"],
        searchText: "elektrostatika  gaya coulomb hukum coulomb",
    },
    {
        id: "medan-listrik",
        url: "elektromagnetisme.html#medan-listrik",
        title: "Medan Listrik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Definisi Medan Listrik",
            "Medan Muatan Titik",
            "Medan Pelat Sejajar",
            "Medan Listrik",
        ],
        searchText:
            "medan listrik  definisi medan listrik medan muatan titik medan pelat sejajar medan listrik",
    },
    {
        id: "gauss",
        url: "elektromagnetisme.html#gauss",
        title: "Hukum Gauss",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Hukum Gauss untuk Listrik", "Hukum Gauss"],
        searchText: "hukum gauss  hukum gauss untuk listrik hukum gauss",
    },
    {
        id: "potensial-listrik",
        url: "elektromagnetisme.html#potensial-listrik",
        title: "Potensial Listrik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Potensial Muatan Titik",
            "Energi Potensial",
            "Hubungan E dan V",
            "Kerja Pindahkan Muatan",
            "Potensial Listrik",
        ],
        searchText:
            "potensial listrik  potensial muatan titik energi potensial hubungan e dan v kerja pindahkan muatan potensial listrik",
    },
    {
        id: "kapasitor",
        url: "elektromagnetisme.html#kapasitor",
        title: "Kapasitor",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Kapasitansi",
            "Kapasitor Pelat Sejajar",
            "Energi Kapasitor",
            "Kapasitor Seri",
            "Kapasitor Paralel",
            "Kapasitor",
        ],
        searchText:
            "kapasitor  kapasitansi kapasitor pelat sejajar energi kapasitor kapasitor seri kapasitor paralel kapasitor",
    },
    {
        id: "arus-listrik",
        url: "elektromagnetisme.html#arus-listrik",
        title: "Arus Listrik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Hukum Ohm", "Hambatan", "Pengaruh Suhu"],
        searchText: "arus listrik  hukum ohm hambatan pengaruh suhu hukum ohm",
    },
    {
        id: "kirchhoff",
        url: "elektromagnetisme.html#kirchhoff",
        title: "Hukum Kirchhoff",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet:
            '"Jumlah arus yang masuk ke sebuah titik cabang sama dengan jumlah arus yang keluar."',
        keywords: [
            "Hukum Kirchhoff",
            "Hukum Arus Kirchhoff (KCL)",
            "Hukum Tegangan Kirchhoff (KVL)",
        ],
        searchText:
            'hukum kirchhoff "jumlah arus yang masuk ke sebuah titik cabang sama dengan jumlah arus yang keluar." hukum kirchhoff hukum arus kirchhoff (kcl) hukum tegangan kirchhoff (kvl)',
    },
    {
        id: "rangkaian-dc",
        url: "elektromagnetisme.html#rangkaian-dc",
        title: "Rangkaian DC",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Hambatan Seri", "Hambatan Paralel", "Rangkaian RC (Pengisian)", "Rangkaian DC"],
        searchText:
            "rangkaian dc  hambatan seri hambatan paralel rangkaian rc (pengisian) rangkaian dc",
    },
    {
        id: "energi-listrik",
        url: "elektromagnetisme.html#energi-listrik",
        title: "Energi & Daya Listrik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Daya Listrik",
            "Energi Listrik",
            "GGL dan Hambatan Dalam",
            "Energi & Daya Listrik",
        ],
        searchText:
            "energi & daya listrik  daya listrik energi listrik ggl dan hambatan dalam energi & daya listrik",
    },
    {
        id: "magnetostatika",
        url: "elektromagnetisme.html#magnetostatika",
        title: "Magnetostatika",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet:
            "Medan magnet dihasilkan oleh muatan bergerak atau arus listrik. Satuannya Tesla (T) = Wb/m².",
        keywords: ["Medan Magnet"],
        searchText:
            "magnetostatika medan magnet dihasilkan oleh muatan bergerak atau arus listrik. satuannya tesla (t) = wb/m². medan magnet",
    },
    {
        id: "biot-savart",
        url: "elektromagnetisme.html#biot-savart",
        title: "Hukum Biot-Savart",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Hukum Biot-Savart (Elemen Arus)", "Hukum Biot-Savart"],
        searchText: "hukum biot-savart  hukum biot-savart (elemen arus) hukum biot-savart",
    },
    {
        id: "ampere",
        url: "elektromagnetisme.html#ampere",
        title: "Hukum Ampere",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Hukum Ampere"],
        searchText: "hukum ampere  hukum ampere hukum ampere",
    },
    {
        id: "lorentz",
        url: "elektromagnetisme.html#lorentz",
        title: "Gaya Lorentz",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Gaya pada Muatan Bergerak",
            "Komponen Magnetik",
            "Gaya pada Kawat Berarus",
            "Gerak Melingkar dalam B",
            "Gaya Lorentz",
        ],
        searchText:
            "gaya lorentz  gaya pada muatan bergerak komponen magnetik gaya pada kawat berarus gerak melingkar dalam b gaya lorentz",
    },
    {
        id: "fluks",
        url: "elektromagnetisme.html#fluks",
        title: "Induksi Elektromagnetik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Fluks Magnetik"],
        searchText: "induksi elektromagnetik  fluks magnetik fluks magnetik",
    },
    {
        id: "faraday",
        url: "elektromagnetisme.html#faraday",
        title: "Hukum Faraday & Hukum Lenz",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Hukum Faraday",
            "GGL Gerak (Motional EMF)",
            "GGL Sinusoidal",
            "Hukum Faraday & Hukum Lenz",
        ],
        searchText:
            "hukum faraday & hukum lenz  hukum faraday ggl gerak (motional emf) ggl sinusoidal hukum faraday & hukum lenz",
    },
    {
        id: "induktansi",
        url: "elektromagnetisme.html#induktansi",
        title: "Induktansi & Transformator",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Induktansi Diri",
            "Induktansi Solenoida",
            "Energi Induktor",
            "Transformator Ideal",
            "Induktansi & Transformator",
        ],
        searchText:
            "induktansi & transformator  induktansi diri induktansi solenoida energi induktor transformator ideal induktansi & transformator",
    },
    {
        id: "rangkaian-ac",
        url: "elektromagnetisme.html#rangkaian-ac",
        title: "Rangkaian AC",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: [
            "Tegangan & Arus AC",
            "Reaktansi Kapasitor",
            "Reaktansi Induktor",
            "Impedansi RLC Seri",
            "Daya AC",
            "Frekuensi Resonansi RLC",
        ],
        searchText:
            "rangkaian ac  tegangan & arus ac reaktansi kapasitor reaktansi induktor impedansi rlc seri daya ac frekuensi resonansi rlc",
    },
    {
        id: "maxwell",
        url: "elektromagnetisme.html#maxwell",
        title: "Persamaan Maxwell",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet:
            "Persamaan Maxwell adalah empat persamaan yang menyatukan listrik, magnet, dan cahaya:",
        keywords: ["Kecepatan Cahaya dari Persamaan Maxwell"],
        searchText:
            "persamaan maxwell persamaan maxwell adalah empat persamaan yang menyatukan listrik, magnet, dan cahaya: kecepatan cahaya dari persamaan maxwell",
    },
    {
        id: "spektrum-em",
        url: "elektromagnetisme.html#spektrum-em",
        title: "Spektrum Elektromagnetik",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet: "",
        keywords: ["Energi Foton"],
        searchText: "spektrum elektromagnetik  energi foton",
    },
    {
        id: "osn-em",
        url: "elektromagnetisme.html#osn-em",
        title: "Contoh Soal",
        topic: "elektromagnetisme",
        topicLabel: "Elektromagnetisme",
        icon: "zap",
        snippet:
            "Sebuah rangkaian RLC seri terdiri dari resistor , induktor , dan kapasitor . Rangkaian dihubungkan ke sumber tegangan AC: dengan .",
        keywords: [],
        searchText:
            "contoh soal sebuah rangkaian rlc seri terdiri dari resistor , induktor , dan kapasitor . rangkaian dihubungkan ke sumber tegangan ac: dengan . ",
    },
    {
        id: "pemantulan",
        url: "optika.html#pemantulan",
        title: "Optika Geometri",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "1. Sinar datang, garis normal, dan sinar pantul berada pada satu bidang datar.",
        keywords: ["Pemantulan Cahaya", "Hukum Pemantulan"],
        searchText:
            "optika geometri 1. sinar datang, garis normal, dan sinar pantul berada pada satu bidang datar. pemantulan cahaya hukum pemantulan",
    },
    {
        id: "cermin",
        url: "optika.html#cermin",
        title: "Cermin Lengkung",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "F C Benda Cermin Cekung Pembentukan bayangan pada cermin cekung (benda di luar C)",
        keywords: ["Persamaan Cermin", "Pembesaran Lateral", "Cermin Lengkung"],
        searchText:
            "cermin lengkung f c benda cermin cekung pembentukan bayangan pada cermin cekung (benda di luar c) persamaan cermin pembesaran lateral cermin lengkung",
    },
    {
        id: "pembiasan",
        url: "optika.html#pembiasan",
        title: "Hukum Snell — Pembiasan Cahaya",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [
            "Hukum Snell-Descartes",
            "Indeks Bias",
            "Hubungan Relatif",
            "Hukum Snell — Pembiasan Cahaya",
        ],
        searchText:
            "hukum snell — pembiasan cahaya  hukum snell-descartes indeks bias hubungan relatif hukum snell — pembiasan cahaya",
    },
    {
        id: "tir",
        url: "optika.html#tir",
        title: "Pemantulan Total Dalam (TIR)",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "Terjadi ketika cahaya bergerak dari medium rapat ke renggang dan sudut datang melebihi sudut kritis.",
        keywords: ["Sudut Kritis", "Pemantulan Total Dalam (TIR)"],
        searchText:
            "pemantulan total dalam (tir) terjadi ketika cahaya bergerak dari medium rapat ke renggang dan sudut datang melebihi sudut kritis. sudut kritis pemantulan total dalam (tir)",
    },
    {
        id: "lensa-cermin",
        url: "optika.html#lensa-cermin",
        title: "Lensa Tipis",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [
            "Persamaan Lensa Tipis (Gauss)",
            "Persamaan Pembuat Lensa (Lensmaker)",
            "Kuat Lensa (Diopter)",
            "Lensa Tipis",
        ],
        searchText:
            "lensa tipis  persamaan lensa tipis (gauss) persamaan pembuat lensa (lensmaker) kuat lensa (diopter) lensa tipis",
    },
    {
        id: "dispersi",
        url: "optika.html#dispersi",
        title: "Dispersi & Prisma",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "Dispersi adalah pemisahan cahaya putih menjadi spektrum warna karena indeks bias bergantung pada panjang gelombang ().",
        keywords: ["Sudut Deviasi Prisma", "Dispersi & Prisma", "Urutan Spektrum Cahaya Tampak"],
        searchText:
            "dispersi & prisma dispersi adalah pemisahan cahaya putih menjadi spektrum warna karena indeks bias bergantung pada panjang gelombang (). sudut deviasi prisma dispersi & prisma urutan spektrum cahaya tampak",
    },
    {
        id: "optika-fisis",
        url: "optika.html#optika-fisis",
        title: "Optika Fisis",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [],
        searchText: "optika fisis  ",
    },
    {
        id: "interferensi",
        url: "optika.html#interferensi",
        title: "Contoh Soal",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "Percobaan Young menunjukkan sifat gelombang cahaya melalui pola interferensi terang-gelap pada layar.",
        keywords: [
            "Beda Lintasan",
            "Terang (Konstruktif)",
            "Gelap (Destruktif)",
            "Jarak Antar Garis Terang",
            "Interferensi — Celah Ganda Young",
        ],
        searchText:
            "contoh soal percobaan young menunjukkan sifat gelombang cahaya melalui pola interferensi terang-gelap pada layar. beda lintasan terang (konstruktif) gelap (destruktif) jarak antar garis terang interferensi — celah ganda young",
    },
    {
        id: "lapisan-tipis",
        url: "optika.html#lapisan-tipis",
        title: "Interferensi pada Lapisan Tipis",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "Terjadi antara sinar yang dipantulkan dari permukaan atas dan bawah lapisan tipis (mis. gelembung sabun, minyak di air).",
        keywords: ["Kondisi Interferensi (Pantulan Normal)", "Interferensi pada Lapisan Tipis"],
        searchText:
            "interferensi pada lapisan tipis terjadi antara sinar yang dipantulkan dari permukaan atas dan bawah lapisan tipis (mis. gelembung sabun, minyak di air). kondisi interferensi (pantulan normal) interferensi pada lapisan tipis",
    },
    {
        id: "difraksi",
        url: "optika.html#difraksi",
        title: "Difraksi",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [
            "Minimum Difraksi Celah Tunggal",
            "Maksimum Kisi Difraksi",
            "Daya Resolusi Kisi",
            "Sudut Resolusi Minimum",
            "Difraksi",
        ],
        searchText:
            "difraksi  minimum difraksi celah tunggal maksimum kisi difraksi daya resolusi kisi sudut resolusi minimum difraksi",
    },
    {
        id: "polarisasi",
        url: "optika.html#polarisasi",
        title: "Polarisasi Cahaya",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet:
            "Cahaya tak terpolarisasi bergetar di semua arah tegak lurus rambat. Polarisasi membatasi getaran pada satu arah saja.",
        keywords: ["Hukum Malus", "Sudut Brewster", "Polarisasi Cahaya"],
        searchText:
            "polarisasi cahaya cahaya tak terpolarisasi bergetar di semua arah tegak lurus rambat. polarisasi membatasi getaran pada satu arah saja. hukum malus sudut brewster polarisasi cahaya",
    },
    {
        id: "alat-optik",
        url: "optika.html#alat-optik",
        title: "Alat-Alat Optik",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [],
        searchText: "alat-alat optik  ",
    },
    {
        id: "mata",
        url: "optika.html#mata",
        title: "Mata Manusia & Cacat Mata",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: ["Mata Manusia & Cacat Mata"],
        searchText: "mata manusia & cacat mata  mata manusia & cacat mata",
    },
    {
        id: "lup",
        url: "optika.html#lup",
        title: "Lup (Kaca Pembesar)",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: [
            "Perbesaran (Mata Berakomodasi Maks)",
            "Perbesaran (Mata Tak Berakomodasi)",
            "Lup (Kaca Pembesar)",
        ],
        searchText:
            "lup (kaca pembesar)  perbesaran (mata berakomodasi maks) perbesaran (mata tak berakomodasi) lup (kaca pembesar)",
    },
    {
        id: "mikroskop",
        url: "optika.html#mikroskop",
        title: "Mikroskop",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "Mikroskop menggunakan dua lensa: objektif (f_ob kecil) dan okuler (f_ok).",
        keywords: ["Perbesaran Total Mikroskop", "Perbesaran Objektif (Pendekatan)", "Mikroskop"],
        searchText:
            "mikroskop mikroskop menggunakan dua lensa: objektif (f_ob kecil) dan okuler (f_ok). perbesaran total mikroskop perbesaran objektif (pendekatan) mikroskop",
    },
    {
        id: "teleskop",
        url: "optika.html#teleskop",
        title: "Teleskop",
        topic: "optika",
        topicLabel: "Optika",
        icon: "eye",
        snippet: "",
        keywords: ["Perbesaran Angular", "Perbesaran", "Teleskop"],
        searchText: "teleskop  perbesaran angular perbesaran teleskop",
    },
    {
        id: "relativitas",
        url: "Fisika-modern.html#relativitas",
        title: "Relativitas Khusus Einstein",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet:
            "Hukum-hukum Fisika berlaku sama dalam semua kerangka acuan inersial (bergerak lurus beraturan).",
        keywords: [
            "Faktor Lorentz (γ)",
            "Dua Postulat Einstein (1905)",
            "Postulat I — Relativitas",
            "Postulat II — Kecepatan Cahaya",
        ],
        searchText:
            "relativitas khusus einstein hukum-hukum Fisika berlaku sama dalam semua kerangka acuan inersial (bergerak lurus beraturan). faktor lorentz (γ) dua postulat einstein (1905) postulat i — relativitas postulat ii — kecepatan cahaya",
    },
    {
        id: "dilatasi",
        url: "Fisika-modern.html#dilatasi",
        title: "Dilatasi Waktu",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: ["Dilatasi Waktu", "Kontraksi Panjang", "Kontraksi Panjang (Lorentz)"],
        searchText:
            "dilatasi waktu  dilatasi waktu kontraksi panjang dilatasi waktu kontraksi panjang (lorentz)",
    },
    {
        id: "relativitas-massa",
        url: "Fisika-modern.html#relativitas-massa",
        title: "Momentum & Massa Relativistik",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: ["Momentum Relativistik", "Massa Relativistik", "Momentum & Massa Relativistik"],
        searchText:
            "momentum & massa relativistik  momentum relativistik massa relativistik momentum & massa relativistik",
    },
    {
        id: "energi-massa",
        url: "Fisika-modern.html#energi-massa",
        title: "Kesetaraan Massa–Energi",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "1 eV = 1,602 × 10⁻¹⁹ J | 1 MeV = 10⁶ eV | 1 GeV = 10⁹ eV",
        keywords: [
            "Energi Total Relativistik",
            "Energi Diam",
            "Energi Kinetik Relativistik",
            "Hubungan E–p",
            "Untuk Foton (m₀ = 0)",
            "Kesetaraan Massa–Energi",
            "Satuan Energi dalam Fisika Partikel",
        ],
        searchText:
            "kesetaraan massa–energi 1 ev = 1,602 × 10⁻¹⁹ j | 1 mev = 10⁶ ev | 1 gev = 10⁹ ev energi total relativistik energi diam energi kinetik relativistik hubungan e–p untuk foton (m₀ = 0) kesetaraan massa–energi satuan energi dalam Fisika partikel",
    },
    {
        id: "transformasi",
        url: "Fisika-modern.html#transformasi",
        title: "Transformasi Lorentz",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: [
            "Transformasi Koordinat (S → S', S' bergerak dengan v ke kanan)",
            "Penjumlahan Kecepatan Relativistik",
            "Transformasi Lorentz",
        ],
        searchText:
            "transformasi lorentz  transformasi koordinat (s → s', s' bergerak dengan v ke kanan) penjumlahan kecepatan relativistik transformasi lorentz",
    },
    {
        id: "planck",
        url: "Fisika-modern.html#planck",
        title: "Awal Mekanika Kuantum",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: [
            "Hukum Pergeseran Wien",
            "Hukum Stefan-Boltzmann",
            "Hipotesis Planck: Kuantisasi Energi",
            "Rumus Radiasi Planck",
            "Radiasi Benda Hitam & Hipotesis Planck",
        ],
        searchText:
            "awal mekanika kuantum  hukum pergeseran wien hukum stefan-boltzmann hipotesis planck: kuantisasi energi rumus radiasi planck radiasi benda hitam & hipotesis planck",
    },
    {
        id: "fotolistrik",
        url: "Fisika-modern.html#fotolistrik",
        title: "Efek Fotolistrik (Einstein, 1905)",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet:
            "Cahaya menumbuk permukaan logam dan mengeluarkan elektron. Energi foton diserap satu-satu oleh elektron.",
        keywords: [
            "Persamaan Efek Fotolistrik",
            "Tegangan Penghenti",
            "Efek Fotolistrik (Einstein, 1905)",
        ],
        searchText:
            "efek fotolistrik (einstein, 1905) cahaya menumbuk permukaan logam dan mengeluarkan elektron. energi foton diserap satu-satu oleh elektron. persamaan efek fotolistrik tegangan penghenti efek fotolistrik (einstein, 1905)",
    },
    {
        id: "compton",
        url: "Fisika-modern.html#compton",
        title: "Efek Compton",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet:
            "Hamburan foton oleh elektron bebas menghasilkan pergeseran panjang gelombang foton — bukti momentum foton.",
        keywords: ["Pergeseran Compton", "Efek Compton"],
        searchText:
            "efek compton hamburan foton oleh elektron bebas menghasilkan pergeseran panjang gelombang foton — bukti momentum foton. pergeseran compton efek compton",
    },
    {
        id: "de-broglie",
        url: "Fisika-modern.html#de-broglie",
        title: "Dualisme Gelombang–Partikel (de Broglie)",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: ["Panjang Gelombang de Broglie", "Dualisme Gelombang–Partikel (de Broglie)"],
        searchText:
            "dualisme gelombang–partikel (de broglie)  panjang gelombang de broglie dualisme gelombang–partikel (de broglie)",
    },
    {
        id: "heisenberg",
        url: "Fisika-modern.html#heisenberg",
        title: "Mekanika Kuantum Dasar",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: [
            "Ketidakpastian Posisi–Momentum",
            "Ketidakpastian Energi–Waktu",
            "Prinsip Ketidakpastian Heisenberg",
        ],
        searchText:
            "mekanika kuantum dasar  ketidakpastian posisi–momentum ketidakpastian energi–waktu prinsip ketidakpastian heisenberg",
    },
    {
        id: "schrodinger",
        url: "Fisika-modern.html#schrodinger",
        title: "Persamaan Schrödinger",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "",
        keywords: [
            "Persamaan Schrödinger Bergantung Waktu",
            "Persamaan Schrödinger Tak Bergantung Waktu",
            "Persamaan Schrödinger",
        ],
        searchText:
            "persamaan schrödinger  persamaan schrödinger bergantung waktu persamaan schrödinger tak bergantung waktu persamaan schrödinger",
    },
    {
        id: "kotak",
        url: "Fisika-modern.html#kotak",
        title: "Partikel dalam Kotak (Sumur Potensial Tak Terhingga)",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet: "Partikel dalam kotak 1D dengan dinding tak tembus (V = ∞ di luar 0 < x < L):",
        keywords: [
            "Fungsi Gelombang",
            "Energi Terkuantisasi",
            "Partikel dalam Kotak (Sumur Potensial Tak Terhingga)",
        ],
        searchText:
            "partikel dalam kotak (sumur potensial tak terhingga) partikel dalam kotak 1d dengan dinding tak tembus (v = ∞ di luar 0 < x < l): fungsi gelombang energi terkuantisasi partikel dalam kotak (sumur potensial tak terhingga)",
    },
    {
        id: "terobosan",
        url: "Fisika-modern.html#terobosan",
        title: "Efek Terobosan Kuantum (Quantum Tunneling)",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet:
            "Partikel dapat menembus penghalang potensial meskipun energinya lebih kecil dari tinggi penghalang — fenomena yang tidak ada analog klasiknya.",
        keywords: [
            "Koefisien Transmisi (Penghalang Tipis)",
            "Efek Terobosan Kuantum (Quantum Tunneling)",
            "Fusi Nuklir di Matahari",
            "Peluruhan Alpha",
            "Scanning Tunneling Microscope",
        ],
        searchText:
            "efek terobosan kuantum (quantum tunneling) partikel dapat menembus penghalang potensial meskipun energinya lebih kecil dari tinggi penghalang — fenomena yang tidak ada analog klasiknya. koefisien transmisi (penghalang tipis) efek terobosan kuantum (quantum tunneling) fusi nuklir di matahari peluruhan alpha scanning tunneling microscope",
    },
    {
        id: "osn-soal",
        url: "Fisika-modern.html#osn-soal",
        title: "Contoh Soal",
        topic: "Fisika-modern",
        topicLabel: "Fisika Modern",
        icon: "clock",
        snippet:
            "Sebuah proton () bergerak dengan energi kinetik menumbuk proton lain yang diam. Reaksi yang mungkin terjadi adalah , dengan massa pion netral .",
        keywords: [],
        searchText:
            "contoh soal sebuah proton () bergerak dengan energi kinetik menumbuk proton lain yang diam. reaksi yang mungkin terjadi adalah , dengan massa pion netral . ",
    },
    {
        id: "model-atom",
        url: "Fisika-atom.html#model-atom",
        title: "Perkembangan Model Atom",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: [],
        searchText: "perkembangan model atom  ",
    },
    {
        id: "thomson",
        url: "Fisika-atom.html#thomson",
        title: "Model Atom Thomson (1897)",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Atom adalah bola bermuatan positif yang merata, dengan elektron-elektron (bermuatan negatif) tersebar di dalamnya seperti buah plum dalam puding.",
        keywords: ["Model Atom Thomson (1897)", 'Model "Puding Prem" (Plum Pudding)'],
        searchText:
            'model atom thomson (1897) atom adalah bola bermuatan positif yang merata, dengan elektron-elektron (bermuatan negatif) tersebar di dalamnya seperti buah plum dalam puding. model atom thomson (1897) model "puding prem" (plum pudding)',
    },
    {
        id: "rutherford",
        url: "Fisika-atom.html#rutherford",
        title: "Model Atom Rutherford (1911)",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Percobaan hamburan partikel alfa (Geiger-Marsden) menunjukkan bahwa sebagian besar massa dan semua muatan positif atom terpusat di inti yang sangat ke",
        keywords: [
            "Model Atom Rutherford (1911)",
            "Temuan Rutherford",
            "Kelemahan Model Rutherford",
        ],
        searchText:
            "model atom rutherford (1911) percobaan hamburan partikel alfa (geiger-marsden) menunjukkan bahwa sebagian besar massa dan semua muatan positif atom terpusat di inti yang sangat ke model atom rutherford (1911) temuan rutherford kelemahan model rutherford",
    },
    {
        id: "atom-bohr",
        url: "Fisika-atom.html#atom-bohr",
        title: "Model Atom Bohr (1913)",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: [
            "Kuantisasi Momentum Sudut",
            "Jari-jari Orbit Bohr",
            "Energi Orbit ke-n (Hidrogen)",
            "Energi Foton yang Dipancarkan",
            "Rumus Rydberg",
            "Perumuman untuk Ion Hidrogenik (Z proton)",
            "Model Atom Bohr (1913)",
        ],
        searchText:
            "model atom bohr (1913)  kuantisasi momentum sudut jari-jari orbit bohr energi orbit ke-n (hidrogen) energi foton yang dipancarkan rumus rydberg perumuman untuk ion hidrogenik (z proton) model atom bohr (1913)",
    },
    {
        id: "spektrum",
        url: "Fisika-atom.html#spektrum",
        title: "Spektrum Atom Hidrogen",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: [],
        searchText: "spektrum atom hidrogen  ",
    },
    {
        id: "deret",
        url: "Fisika-atom.html#deret",
        title: "Deret Spektrum Hidrogen",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: ["Deret Spektrum Hidrogen"],
        searchText: "deret spektrum hidrogen  deret spektrum hidrogen",
    },
    {
        id: "emisi-absorpsi",
        url: "Fisika-atom.html#emisi-absorpsi",
        title: "Contoh Soal",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Gas dipanaskan → elektron tereksitasi ke level lebih tinggi → jatuh kembali → memancarkan foton dengan frekuensi spesifik.",
        keywords: ["Spektrum Emisi & Absorpsi", "Spektrum Emisi", "Spektrum Absorpsi"],
        searchText:
            "contoh soal gas dipanaskan → elektron tereksitasi ke level lebih tinggi → jatuh kembali → memancarkan foton dengan frekuensi spesifik. spektrum emisi & absorpsi spektrum emisi spektrum absorpsi",
    },
    {
        id: "bilangan-kuantum",
        url: "Fisika-atom.html#bilangan-kuantum",
        title: "Bilangan Kuantum",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Model mekanika kuantum atom hidrogen (Schrödinger) menghasilkan empat bilangan kuantum untuk mendeskripsikan setiap keadaan elektron:",
        keywords: [],
        searchText:
            "bilangan kuantum model mekanika kuantum atom hidrogen (schrödinger) menghasilkan empat bilangan kuantum untuk mendeskripsikan setiap keadaan elektron: ",
    },
    {
        id: "orbital",
        url: "Fisika-atom.html#orbital",
        title: "Orbital Atom",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: ["Orbital Atom"],
        searchText: "orbital atom  orbital atom",
    },
    {
        id: "konfigurasi",
        url: "Fisika-atom.html#konfigurasi",
        title: "Konfigurasi Elektron",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "",
        keywords: ["Urutan Pengisian Orbital (Aturan Aufbau)", "Konfigurasi Elektron"],
        searchText:
            "konfigurasi elektron  urutan pengisian orbital (aturan aufbau) konfigurasi elektron",
    },
    {
        id: "pauli",
        url: "Fisika-atom.html#pauli",
        title: "Asas Larangan Pauli",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Akibatnya: setiap orbital paling banyak ditempati oleh 2 elektron dengan spin berlawanan (↑↓).",
        keywords: ["Asas Larangan Pauli"],
        searchText:
            "asas larangan pauli akibatnya: setiap orbital paling banyak ditempati oleh 2 elektron dengan spin berlawanan (↑↓). asas larangan pauli",
    },
    {
        id: "hund",
        url: "Fisika-atom.html#hund",
        title: "Aturan Hund",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet:
            "Elektron mengisi orbital-orbital yang setingkat (degenerate) satu per satu dengan spin searah terlebih dahulu, sebelum memasangkan diri.",
        keywords: ["Aturan Hund", "Aturan Hund (Stabilitas Maksimum)"],
        searchText:
            "aturan hund elektron mengisi orbital-orbital yang setingkat (degenerate) satu per satu dengan spin searah terlebih dahulu, sebelum memasangkan diri. aturan hund aturan hund (stabilitas maksimum)",
    },
    {
        id: "ikatan",
        url: "Fisika-atom.html#ikatan",
        title: "Fisika Molekul",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "Atom-atom berbagi pasangan elektron. Sangat kuat. Contoh: H₂, O₂, H₂O, CO₂.",
        keywords: ["Jenis Ikatan Kimia", "Ikatan Kovalen", "Ikatan Ion", "Ikatan Logam"],
        searchText:
            "Fisika molekul atom-atom berbagi pasangan elektron. sangat kuat. contoh: h₂, o₂, h₂o, co₂. jenis ikatan kimia ikatan kovalen ikatan ion ikatan logam",
    },
    {
        id: "spektrum-mol",
        url: "Fisika-atom.html#spektrum-mol",
        title: "Spektrum Molekul",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "Molekul memiliki tiga mode penyimpanan energi yang dapat terkuantisasi:",
        keywords: [
            "Energi Rotasi Molekul Diatomik",
            "Energi Vibrasi (Osilator Harmonik Kuantum)",
            "Spektrum Molekul",
        ],
        searchText:
            "spektrum molekul molekul memiliki tiga mode penyimpanan energi yang dapat terkuantisasi: energi rotasi molekul diatomik energi vibrasi (osilator harmonik kuantum) spektrum molekul",
    },
    {
        id: "laser",
        url: "Fisika-atom.html#laser",
        title: "Laser (Light Amplification by Stimulated Emission of Radiation)",
        topic: "Fisika-atom",
        topicLabel: "Fisika Atom",
        icon: "target",
        snippet: "Laser menghasilkan cahaya koheren melalui emisi terstimulasi.",
        keywords: [
            "Laser (Light Amplification by Stimulated Emission of Radiation)",
            "Emisi Spontan",
            "Emisi Terstimulasi",
            "Inversi Populasi",
        ],
        searchText:
            "laser (light amplification by stimulated emission of radiation) laser menghasilkan cahaya koheren melalui emisi terstimulasi. laser (light amplification by stimulated emission of radiation) emisi spontan emisi terstimulasi inversi populasi",
    },
    {
        id: "struktur-inti",
        url: "Fisika-nuklir.html#struktur-inti",
        title: "Struktur Inti Atom",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            "Isotop: nuklida dengan Z sama, A berbeda. Contoh: ¹H, ²H (deuterium), ³H (tritium).",
        keywords: ["Notasi Nuklida", "Proton & Neutron"],
        searchText:
            "struktur inti atom isotop: nuklida dengan z sama, a berbeda. contoh: ¹h, ²h (deuterium), ³h (tritium). notasi nuklida proton & neutron",
    },
    {
        id: "defek-massa",
        url: "Fisika-nuklir.html#defek-massa",
        title: "Defek Massa & Energi Ikat Inti",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            "Massa inti selalu lebih kecil dari jumlah massa proton dan neutron penyusunnya. Selisihnya disebut defek massa , yang dikonversi menjadi energi ikat.",
        keywords: [
            "Defek Massa",
            "Energi Ikat (Binding Energy)",
            "Energi Ikat per Nukleon",
            "Defek Massa & Energi Ikat Inti",
        ],
        searchText:
            "defek massa & energi ikat inti massa inti selalu lebih kecil dari jumlah massa proton dan neutron penyusunnya. selisihnya disebut defek massa , yang dikonversi menjadi energi ikat. defek massa energi ikat (binding energy) energi ikat per nukleon defek massa & energi ikat inti",
    },
    {
        id: "gaya-nuklir",
        url: "Fisika-nuklir.html#gaya-nuklir",
        title: "Gaya Nuklir Kuat (Strong Force)",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "",
        keywords: ["Gaya Nuklir Kuat (Strong Force)"],
        searchText: "gaya nuklir kuat (strong force)  gaya nuklir kuat (strong force)",
    },
    {
        id: "stabilitas",
        url: "Fisika-nuklir.html#stabilitas",
        title: "Stabilitas Inti & Pita Stabilitas",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            'Plot jumlah proton (Z) vs neutron (N) menunjukkan "pita stabilitas" — inti stabil terkonsentrasi di sepanjang garis N ≈ Z (untuk inti ringan) hingga N',
        keywords: ["Stabilitas Inti & Pita Stabilitas"],
        searchText:
            'stabilitas inti & pita stabilitas plot jumlah proton (z) vs neutron (n) menunjukkan "pita stabilitas" — inti stabil terkonsentrasi di sepanjang garis n ≈ z (untuk inti ringan) hingga n stabilitas inti & pita stabilitas',
    },
    {
        id: "radioaktivitas",
        url: "Fisika-nuklir.html#radioaktivitas",
        title: "Radioaktivitas",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "",
        keywords: ["Aktivitas", "Konstanta Peluruhan", "Definisi & Aktivitas"],
        searchText: "radioaktivitas  aktivitas konstanta peluruhan definisi & aktivitas",
    },
    {
        id: "peluruhan",
        url: "Fisika-nuklir.html#peluruhan",
        title: "Jenis Peluruhan Radioaktif",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "Jangkauan pendek di udara (~cm). Dihentikan kertas. Ionisasi kuat.",
        keywords: [
            "Jenis Peluruhan Radioaktif",
            "Peluruhan Alpha (α)",
            "Peluruhan Beta (β)",
            "Peluruhan Gamma (γ)",
            "Tangkap Elektron (Electron Capture)",
        ],
        searchText:
            "jenis peluruhan radioaktif jangkauan pendek di udara (~cm). dihentikan kertas. ionisasi kuat. jenis peluruhan radioaktif peluruhan alpha (α) peluruhan beta (β) peluruhan gamma (γ) tangkap elektron (electron capture)",
    },
    {
        id: "waktu-paruh",
        url: "Fisika-nuklir.html#waktu-paruh",
        title: "Contoh Soal",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "Nuklida meluruh secara alfa menjadi . Data massa atomik: , , . .",
        keywords: [
            "Hukum Peluruhan Radioaktif",
            "Aktivitas sebagai Fungsi Waktu",
            "Waktu Paruh & Hukum Peluruhan",
        ],
        searchText:
            "contoh soal nuklida meluruh secara alfa menjadi . data massa atomik: , , . . hukum peluruhan radioaktif aktivitas sebagai fungsi waktu waktu paruh & hukum peluruhan",
    },
    {
        id: "rantai-peluruhan",
        url: "Fisika-nuklir.html#rantai-peluruhan",
        title: "Rantai Peluruhan",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            "Nuklida berat sering meluruh melalui serangkaian peluruhan alfa dan beta sebelum mencapai inti stabil.",
        keywords: ["Rantai Peluruhan", "Deret Uranium-238"],
        searchText:
            "rantai peluruhan nuklida berat sering meluruh melalui serangkaian peluruhan alfa dan beta sebelum mencapai inti stabil. rantai peluruhan deret uranium-238",
    },
    {
        id: "reaksi-nuklir",
        url: "Fisika-nuklir.html#reaksi-nuklir",
        title: "Reaksi Nuklir",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "Dalam semua reaksi nuklir, berlaku hukum kekekalan:",
        keywords: ["Q-Nilai Reaksi", "Dasar Reaksi Nuklir"],
        searchText:
            "reaksi nuklir dalam semua reaksi nuklir, berlaku hukum kekekalan: q-nilai reaksi dasar reaksi nuklir",
    },
    {
        id: "fisi",
        url: "Fisika-nuklir.html#fisi",
        title: "Fisi Nuklir",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            "Inti berat membelah menjadi dua fragmen medium, disertai pelepasan beberapa neutron dan energi besar.",
        keywords: [
            "Contoh Reaksi Fisi Uranium-235",
            "Fisi Nuklir",
            "Reaksi Berantai",
            "Massa Kritis",
        ],
        searchText:
            "fisi nuklir inti berat membelah menjadi dua fragmen medium, disertai pelepasan beberapa neutron dan energi besar. contoh reaksi fisi uranium-235 fisi nuklir reaksi berantai massa kritis",
    },
    {
        id: "fusi",
        url: "Fisika-nuklir.html#fusi",
        title: "Fusi Nuklir",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet:
            "Dua inti ringan bergabung membentuk inti yang lebih berat dan melepaskan energi besar. Ini adalah sumber energi bintang.",
        keywords: [
            "Reaksi D-T (Kandidat Utama Fusi)",
            "Reaksi di Matahari (Rantai p-p)",
            "Fusi Nuklir",
        ],
        searchText:
            "fusi nuklir dua inti ringan bergabung membentuk inti yang lebih berat dan melepaskan energi besar. ini adalah sumber energi bintang. reaksi d-t (kandidat utama fusi) reaksi di matahari (rantai p-p) fusi nuklir",
    },
    {
        id: "aplikasi",
        url: "Fisika-nuklir.html#aplikasi",
        title: "Aplikasi Fisika Nuklir",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "",
        keywords: ["Kedokteran Nuklir", "Energi Nuklir", "Sains & Industri"],
        searchText: "aplikasi Fisika nuklir  kedokteran nuklir energi nuklir sains & industri",
    },
    {
        id: "proteksi",
        url: "Fisika-nuklir.html#proteksi",
        title: "Proteksi Radiasi",
        topic: "Fisika-nuklir",
        topicLabel: "Fisika Nuklir",
        icon: "alert-triangle",
        snippet: "",
        keywords: ["Proteksi Radiasi"],
        searchText: "proteksi radiasi  proteksi radiasi",
    },
    {
        id: "model-standar",
        url: "Fisika-partikel.html#model-standar",
        title: "Model Standar Partikel Elementer",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "",
        keywords: [],
        searchText: "model standar partikel elementer  ",
    },
    {
        id: "klasifikasi",
        url: "Fisika-partikel.html#klasifikasi",
        title: "Klasifikasi Partikel",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "Partikel materi — mengikuti statistik Fermi-Dirac dan asas larangan Pauli.",
        keywords: ["Klasifikasi Partikel", "Fermion (Spin ½)", "Boson (Spin Bulat)"],
        searchText:
            "klasifikasi partikel partikel materi — mengikuti statistik fermi-dirac dan asas larangan pauli. klasifikasi partikel fermion (spin ½) boson (spin bulat)",
    },
    {
        id: "quark-lepton",
        url: "Fisika-partikel.html#quark-lepton",
        title: "Quark",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Quark adalah partikel elementer penyusun hadron. Tidak pernah ditemukan bebas (confinement). Memiliki muatan warna (merah, hijau, biru) dan muatan lis",
        keywords: [],
        searchText:
            "quark quark adalah partikel elementer penyusun hadron. tidak pernah ditemukan bebas (confinement). memiliki muatan warna (merah, hijau, biru) dan muatan lis ",
    },
    {
        id: "lepton",
        url: "Fisika-partikel.html#lepton",
        title: "Lepton",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Lepton tidak berinteraksi melalui gaya kuat — hanya melalui gaya elektromagnetik (jika bermuatan) dan gaya lemah.",
        keywords: ["Lepton"],
        searchText:
            "lepton lepton tidak berinteraksi melalui gaya kuat — hanya melalui gaya elektromagnetik (jika bermuatan) dan gaya lemah. lepton",
    },
    {
        id: "generasi",
        url: "Fisika-partikel.html#generasi",
        title: "Tiga Generasi (Keluarga) Fermion",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "Menyusun semua materi stabil di alam semesta.",
        keywords: [
            "Tiga Generasi (Keluarga) Fermion",
            "Generasi I (Paling Ringan)",
            "Generasi II",
            "Generasi III (Paling Berat)",
        ],
        searchText:
            "tiga generasi (keluarga) fermion menyusun semua materi stabil di alam semesta. tiga generasi (keluarga) fermion generasi i (paling ringan) generasi ii generasi iii (paling berat)",
    },
    {
        id: "boson",
        url: "Fisika-partikel.html#boson",
        title: "Boson Gauge",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "",
        keywords: [],
        searchText: "boson gauge  ",
    },
    {
        id: "gaya-fundamental",
        url: "Fisika-partikel.html#gaya-fundamental",
        title: "Empat Gaya Fundamental",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            'Gluon membawa "muatan warna" — berbeda dengan foton yang netral secara elektromagnetik. Ada 8 gluon berbeda. Kekuatan gaya kuat meningkat dengan jarak',
        keywords: [
            "Empat Gaya Fundamental",
            "Gaya Kuat — Kromodinamika Kuantum (QCD)",
            "Gaya Lemah — Penyebab Peluruhan Beta",
        ],
        searchText:
            'empat gaya fundamental gluon membawa "muatan warna" — berbeda dengan foton yang netral secara elektromagnetik. ada 8 gluon berbeda. kekuatan gaya kuat meningkat dengan jarak empat gaya fundamental gaya kuat — kromodinamika kuantum (qcd) gaya lemah — penyebab peluruhan beta',
    },
    {
        id: "higgs",
        url: "Fisika-partikel.html#higgs",
        title: "Boson Higgs & Mekanisme Higgs",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Boson Higgs adalah partikel terakhir Model Standar yang ditemukan, dikonfirmasi oleh LHC CERN pada 4 Juli 2012 .",
        keywords: ["Massa Boson Higgs", "Boson Higgs & Mekanisme Higgs", "Mekanisme Higgs"],
        searchText:
            "boson higgs & mekanisme higgs boson higgs adalah partikel terakhir model standar yang ditemukan, dikonfirmasi oleh lhc cern pada 4 juli 2012 . massa boson higgs boson higgs & mekanisme higgs mekanisme higgs",
    },
    {
        id: "hadron",
        url: "Fisika-partikel.html#hadron",
        title: "Hadron",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Hadron adalah partikel yang tersusun dari quark dan terikat oleh gaya kuat. Terbagi dua:",
        keywords: ["Muatan Listrik Barion", "Barion (3 Quark)", "Meson (Quark + Antiquark)"],
        searchText:
            "hadron hadron adalah partikel yang tersusun dari quark dan terikat oleh gaya kuat. terbagi dua: muatan listrik barion barion (3 quark) meson (quark + antiquark)",
    },
    {
        id: "antimateri",
        url: "Fisika-partikel.html#antimateri",
        title: "Antimateri",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Setiap partikel memiliki antipartikel dengan massa sama tetapi muatan berlawanan (dan bilangan kuantum lainnya terbalik).",
        keywords: ["Anihilasi Partikel-Antipartikel"],
        searchText:
            "antimateri setiap partikel memiliki antipartikel dengan massa sama tetapi muatan berlawanan (dan bilangan kuantum lainnya terbalik). anihilasi partikel-antipartikel",
    },
    {
        id: "simetri",
        url: "Fisika-partikel.html#simetri",
        title: "Simetri & Hukum Kekekalan",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "",
        keywords: ["Simetri & Hukum Kekekalan"],
        searchText: "simetri & hukum kekekalan  simetri & hukum kekekalan",
    },
    {
        id: "kosmologi",
        url: "Fisika-partikel.html#kosmologi",
        title: "Kosmologi Partikel",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "",
        keywords: ["Big Bang & Kronologi Alam Semesta Awal"],
        searchText: "kosmologi partikel  big bang & kronologi alam semesta awal",
    },
    {
        id: "materi-gelap",
        url: "Fisika-partikel.html#materi-gelap",
        title: "Materi Gelap & Energi Gelap",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet: "~5% kandungan alam semesta. Terdiri dari atom (barion), bintang, gas, planet.",
        keywords: ["Materi Gelap & Energi Gelap", "Materi Biasa", "Materi Gelap", "Energi Gelap"],
        searchText:
            "materi gelap & energi gelap ~5% kandungan alam semesta. terdiri dari atom (barion), bintang, gas, planet. materi gelap & energi gelap materi biasa materi gelap energi gelap",
    },
    {
        id: "akselerator",
        url: "Fisika-partikel.html#akselerator",
        title: "Akselerator Partikel",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Akselerator partikel adalah alat yang mempercepat partikel bermuatan hingga energi sangat tinggi, digunakan untuk menyelidiki struktur materi pada ska",
        keywords: ["Fisika Partikel — Pertanyaan Terbuka"],
        searchText:
            "akselerator partikel akselerator partikel adalah alat yang mempercepat partikel bermuatan hingga energi sangat tinggi, digunakan untuk menyelidiki struktur materi pada ska Fisika partikel — pertanyaan terbuka",
    },
    {
        id: "osn-partikel",
        url: "Fisika-partikel.html#osn-partikel",
        title: "Contoh Soal",
        topic: "Fisika-partikel",
        topicLabel: "Fisika Partikel",
        icon: "package",
        snippet:
            "Pion bermuatan meluruh menjadi muon dan neutrino muon: . Data massa: , , . Anggap pion diam sebelum meluruh.",
        keywords: [],
        searchText:
            "contoh soal pion bermuatan meluruh menjadi muon dan neutrino muon: . data massa: , , . anggap pion diam sebelum meluruh. ",
    },
];
